_BASE_: ../Base-DeepLabV3-OS16-Semantic.yaml
MODEL:
  WEIGHTS: "/data/new/Experiments/jlgomez/detectron2baselines/custom_synscapes_translated/baseline_deepLabV3plus_crop512_batch4_60k_5000_20c_lr2e-3/model_final.pth"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  BACKBONE:
    NAME: "build_resnet_deeplab_backbone"
  RESNETS:
    DEPTH: 101
    NORM: "BN"
    OUT_FEATURES: ["res2", "res5"]
    RES5_MULTI_GRID: [1, 2, 4]
    STEM_TYPE: "deeplab"
    STEM_OUT_CHANNELS: 128
    STRIDE_IN_1X1: False
  SEM_SEG_HEAD:
    IGNORE_VALUE: 19
    NUM_CLASSES: 20
    NAME: "DeepLabV3PlusHead"
    IN_FEATURES: ["res2", "res5"]
    PROJECT_FEATURES: ["res2"]
    PROJECT_CHANNELS: [48]
    COMMON_STRIDE: 4
    NORM: "BN"
INPUT:
  FORMAT: "RGB"
  ACTIVATE_MIN_SIZE_TRAIN: True
  MIN_SIZE_TRAIN: (512, 768, 1024, 1280, 1536, 1792, 2048)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 4096
  MAX_SIZE_TEST: 2048
  RESIZED: True
  RESIZE_SIZE: (1024, 2048)
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (512, 1024)
    SINGLE_CATEGORY_MAX_AREA: 1.0
  RCS:
    ENABLED: True
    MIN_PIXELS: 3000
    CLASS_TEMP: 0.01
    MIN_CROP_RATIO: 0.5
    STATS_PATH: /datatmp/Datasets/segmentation/GTA/
INPUT2:
  FORMAT: "RGB"
  ACTIVATE_MIN_SIZE_TRAIN: True
  MIN_SIZE_TRAIN: (768, 1024, 1536)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MAX_SIZE_TRAIN: 4096
  RESIZED: True
  RESIZE_SIZE: (1024, 2048)
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (512, 1024)
    SINGLE_CATEGORY_MAX_AREA: 1.0
DATASETS:
  TRAIN_IMG_TXT: /datatmp/Datasets/segmentation/GTA/gta5_rgb_translated.txt
  TRAIN_GT_TXT: /datatmp/Datasets/segmentation/GTA/gta5_gt_full.txt
  TRAIN_IMG_TXT2: /datatmp/Datasets/segmentation/cityscapes/leftimage8bit_train.txt
  TRAIN_GT_TXT2: /data/new/Experiments/jlgomez/cotraining_sem_seg/rcs_experiments/rcs_upper_margin_cotraining_V3plus_GTA_conf_diff_branches_5000p_8k_1_3_100_lr2e-3_20c_scratch_ensembles_classmixV2_seed100_recomp_mtp0.5_0.75_selfpre0_9/final_ensemble/image_list.txt
  TEST_IMG_TXT: /datatmp/Datasets/segmentation/cityscapes/leftimage8bit_val.txt
  TEST_GT_TXT: /datatmp/Datasets/segmentation/cityscapes/gtFine_val.txt
  LABELS: "cityscapes"
SOLVER:
  ALTERNATE_SOURCE_PSEUDOLABELS: True
  SOURCE_PSEUDOLABELS_BATCH_RATIO: (2, 2) # ratio sum must match IMS_PER_BATCH, 1st values source batch size, second values target batch size
  IMS_PER_BATCH: 4
  BASE_LR: 0.002
  STEPS: (15000, 30000, 40000)
  MAX_ITER: 60000
  CHECKPOINT_PERIOD: 10000
TEST:
  EVAL_PERIOD: 5000
OUTPUT_DIR: /data/new/Experiments/jlgomez/detectron2baselines/custom_synscapes_translated+cityscapes_alternated/baseline_deepLabV3plus_crop512_batch4_45k_2500_20c_lr2e-3_upperbound
AUGMENTATION:
  CUTOUT: False
  CUTOUT_N_HOLES: (0, 5)
  CUTOUT_LENGTH: (100, 300)
  RANDOM_RESIZE: False
  RESIZE_RANGE: (0.5, 1.5)
  HFLIP: True
  HFLIP_PROB: 0.5
